### PR TITLE
Unicode problem fixed on Windows 10 x64 JP loc

### PR DESCRIPTION
**Pull request by Kaens**
Before: https://lithi.io/file/kq5Y.png (note how the updates never happen, but the rejections do)
After: https://lithi.io/file/FSDL.png (everything seems to work fine)

### CODE REVIEW

**Comment by Tromador** [comment]
I am unable to view your screenshots - 
```
Secure Connection Failed

An error occurred during a connection to lithi.io. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the web site owners to inform them of this problem.
```

**Comment by Kaens** [comment]
Huh. That's super strange. Okay, now that the UI allows me to upload from clipboard, I'll just do it this way:
Before 
image
After 
image

**Comment by Tromador** [comment]
I see where you are coming from. It will be a specific issue for any systems using a non-latin character set, your fix should cover them all, so we should probably adopt it (though I'll leave eyeonus to make the final decision).

I should say we normally recommend users to not user the listener, but to use [Trade Dangerous](https://forums.frontier.co.uk/threads/trade-dangerous-est-2015-power-users-highly-configurable-trade-optimizer.441509/) which will connect to the server I run.

**Comment by eyeonus** [comment]
I looked at it, and I see nothing wrong, I just want to make sure there
aren't any other places in the code where that should also be done
before I merge.

**Pull request merged**
